name: Deploy esenin-group

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ESENIN_HOST }}
          username: ${{ secrets.ESENIN_USER }}
          key: ${{ secrets.ESENIN_KEY }}
          script: |
            #cd ~/esenin-group/public_html/wp-content/themes/esenin-group
            #git clone git@github.com:site100ru/esenin-group-wp.git .
            #git clone https://github.com/site100ru/esenin-group-wp.git .
            
            cd ~/esenin-group/public_html/wp-content/themes/esenin-group
            git pull
